# Build website
[build]
  command = "yarn run build:prod"
  publish = "docs/dist/"

# Custom 404
[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404

# Terry Pratchett homage
[[headers]]
  for = "/*"
  [headers.values]
    X-Clacks-Overhead = "GNU Terry Pratchett"
